"""Add role to user model

Revision ID: a5adc00d5a7f
Revises: 31c8b4c06c11
Create Date: 2026-01-29 07:13:29.272165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5adc00d5a7f'
down_revision: Union[str, Sequence[str], None] = '31c8b4c06c11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('user', sa.Column('role', sa.String(), nullable=True))
    
    # Set default value for existing users
    op.execute("UPDATE \"user\" SET role = 'user' WHERE role IS NULL")
    
    # Now make it non-nullable
    op.alter_column('user', 'role', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
